{
    "dataFlowType": "standard",
    "mode": "stream",
    "targetFormat": "delta",
    "sourceDetails": {
        "database": "Oracle",
        "table": "failurecode",
        "path": "s3://s3-staging-maximo-dev-apse2-058264204922/internal/MAXIMO/FAILURECODE",
        "readerOptions": {
            "cloudFiles.format": "parquet",
            "cloudFiles.inferColumnTypes": "true",
            "cloudFiles.rescuedDataColumn": "_rescued_data",
            "header": "true"
        }
    },
    "targetDetails": {
        "table": "failurecode",
        "path": "Ignore",
        "tableProperties": {
            "delta.enableChangeDataFeed": "true"
        },
        "schemaPath": "failurecode_schema.json"
    },
    "dataFlowId": "maximo_failurecode",
    "dataFlowGroup": "maximo_bronze",
    "sourceSystem": "maximo",
    "sourceType": "cloudFiles",
    "cdcApplyChanges": {
        "keys": [
            "N/A"
        ],
        "scd_type": "2",
        "except_column_list": [
            "N/A"
        ]
    },
    "sourceViewName": "v_failurecode"
}